// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pkg/auth/proto/auth.proto

package go_micro_service_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Auth service

func NewAuthEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Auth service

type AuthService interface {
	GetPaginated(ctx context.Context, in *RequestPageOptions, opts ...client.CallOption) (*ResponsePage, error)
	GetList(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*ResponseQueryPointsArray, error)
	GetByID(ctx context.Context, in *RequestQueryPointID, opts ...client.CallOption) (*ResponseQueryPoint, error)
	Create(ctx context.Context, in *RequestCreateQueryPoint, opts ...client.CallOption) (*ResponseQueryPoint, error)
	Update(ctx context.Context, in *RequestUpdateQueryPoint, opts ...client.CallOption) (*ResponseQueryPoint, error)
	Delete(ctx context.Context, in *RequestQueryPointID, opts ...client.CallOption) (*ResponseQueryPoint, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) GetPaginated(ctx context.Context, in *RequestPageOptions, opts ...client.CallOption) (*ResponsePage, error) {
	req := c.c.NewRequest(c.name, "Auth.GetPaginated", in)
	out := new(ResponsePage)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetList(ctx context.Context, in *empty.Empty, opts ...client.CallOption) (*ResponseQueryPointsArray, error) {
	req := c.c.NewRequest(c.name, "Auth.GetList", in)
	out := new(ResponseQueryPointsArray)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) GetByID(ctx context.Context, in *RequestQueryPointID, opts ...client.CallOption) (*ResponseQueryPoint, error) {
	req := c.c.NewRequest(c.name, "Auth.GetByID", in)
	out := new(ResponseQueryPoint)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Create(ctx context.Context, in *RequestCreateQueryPoint, opts ...client.CallOption) (*ResponseQueryPoint, error) {
	req := c.c.NewRequest(c.name, "Auth.Create", in)
	out := new(ResponseQueryPoint)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Update(ctx context.Context, in *RequestUpdateQueryPoint, opts ...client.CallOption) (*ResponseQueryPoint, error) {
	req := c.c.NewRequest(c.name, "Auth.Update", in)
	out := new(ResponseQueryPoint)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Delete(ctx context.Context, in *RequestQueryPointID, opts ...client.CallOption) (*ResponseQueryPoint, error) {
	req := c.c.NewRequest(c.name, "Auth.Delete", in)
	out := new(ResponseQueryPoint)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	GetPaginated(context.Context, *RequestPageOptions, *ResponsePage) error
	GetList(context.Context, *empty.Empty, *ResponseQueryPointsArray) error
	GetByID(context.Context, *RequestQueryPointID, *ResponseQueryPoint) error
	Create(context.Context, *RequestCreateQueryPoint, *ResponseQueryPoint) error
	Update(context.Context, *RequestUpdateQueryPoint, *ResponseQueryPoint) error
	Delete(context.Context, *RequestQueryPointID, *ResponseQueryPoint) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		GetPaginated(ctx context.Context, in *RequestPageOptions, out *ResponsePage) error
		GetList(ctx context.Context, in *empty.Empty, out *ResponseQueryPointsArray) error
		GetByID(ctx context.Context, in *RequestQueryPointID, out *ResponseQueryPoint) error
		Create(ctx context.Context, in *RequestCreateQueryPoint, out *ResponseQueryPoint) error
		Update(ctx context.Context, in *RequestUpdateQueryPoint, out *ResponseQueryPoint) error
		Delete(ctx context.Context, in *RequestQueryPointID, out *ResponseQueryPoint) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) GetPaginated(ctx context.Context, in *RequestPageOptions, out *ResponsePage) error {
	return h.AuthHandler.GetPaginated(ctx, in, out)
}

func (h *authHandler) GetList(ctx context.Context, in *empty.Empty, out *ResponseQueryPointsArray) error {
	return h.AuthHandler.GetList(ctx, in, out)
}

func (h *authHandler) GetByID(ctx context.Context, in *RequestQueryPointID, out *ResponseQueryPoint) error {
	return h.AuthHandler.GetByID(ctx, in, out)
}

func (h *authHandler) Create(ctx context.Context, in *RequestCreateQueryPoint, out *ResponseQueryPoint) error {
	return h.AuthHandler.Create(ctx, in, out)
}

func (h *authHandler) Update(ctx context.Context, in *RequestUpdateQueryPoint, out *ResponseQueryPoint) error {
	return h.AuthHandler.Update(ctx, in, out)
}

func (h *authHandler) Delete(ctx context.Context, in *RequestQueryPointID, out *ResponseQueryPoint) error {
	return h.AuthHandler.Delete(ctx, in, out)
}
